version: '3.8'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8761" ]
      interval: 5s
      retries: 3
      start_period: 10s
      timeout: 5s

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - registry.host=eureka-server
      - registry.port=8761

  sms-service:
    build: ./sms-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - registry.host=eureka-server
      - registry.port=8761

  email-service:
    build: ./email-service
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - registry.host=eureka-server
      - registry.port=8761

  push-service:
    build: ./push-service
    ports:
      - "8083:8083"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - registry.host=eureka-server
      - registry.port=8761